name: Parkour
author: SpleefLeague
authors: [Joba, Akaiyo, Manuman]
main: com.spleefleague.parkour.Parkour
version: 1.4
api-version: 1.13
depend: [SpleefLeagueCore, Commands, GameAPI]
commands:    
    parkour:
        description: Parkour queue command
        aliases: [superjump, sj, p]
        usage: |
          /<command> [arena]